<br>!!CUSTOMER_LASTNAME!! - {LBLA_SURENAME} {LBLA_OF} {LBLA_CUSTOMER}<br>
					!!HELLO!! - Anrede {LBLA_OF} {LBLA_CUSTOMER}<br>
					!!EMAIL!! - {LBLA_CUSTOMER} Email<br>
					!!DISABLE_LETTER_LINK!! - {LBLA_DISABLELINK_SENTENCE}<br>
					!!TRACKING_CODE!! - {LBLA_TRACKINGINFO}