<?php

/**
 * @package    sellform
 *
 * @copyright  Copyright (C) 2006 - 2016 Trebaxa GmbH&Co.KG. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE
 * @version    1.2
 */
class PPAutoloader {
    private static $map = array(
        'abstractrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'abstractresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'activationdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'additionalfeetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'addresstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'addressverifyreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'addressverifyrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'addressverifyresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'airlineitinerarytype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'apicredentialstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'attributecontainertestclass' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPMessageTest.php',
        'attributetestclass' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPMessageTest.php',
        'auctioninfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'authorizationinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'authorizationrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'authorizationresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'authsignature' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'bankaccountdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'basicamounttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'baupdaterequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'baupdateresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'baupdateresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billagreementupdatereq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billingagreementdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billingapprovaldetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billingperioddetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billingperioddetailstype_update' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billoutstandingamountreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billoutstandingamountrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billoutstandingamountrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billoutstandingamountresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billoutstandingamountresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billuserreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billuserrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'billuserresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmbuttonsearchreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmbuttonsearchrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmbuttonsearchresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmcreatebuttonreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmcreatebuttonrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmcreatebuttonresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmgetbuttondetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmgetbuttondetailsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmgetbuttondetailsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmgetinventoryreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmgetinventoryrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmgetinventoryresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmlofferinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmmanagebuttonstatusreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmmanagebuttonstatusrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmmanagebuttonstatusresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmsetinventoryreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmsetinventoryrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmsetinventoryresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmupdatebuttonreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmupdatebuttonrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'bmupdatebuttonresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'businessinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'businessownerinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'buttonsearchresulttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'buyerdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'buyerdetailtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'cancelpermissionsrequest' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'cancelpermissionsresponse' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'cancelrecoupreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'cancelrecouprequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'cancelrecoupresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'completerecoupreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'completerecouprequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'completerecoupresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'configuration' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/samples/Configuration.php',
        'coupledbucketstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'coupledpaymentinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createbillingagreementreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createbillingagreementrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createbillingagreementresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createmobilepaymentreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createmobilepaymentrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createmobilepaymentrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createmobilepaymentresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createrecurringpaymentsprofilereq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createrecurringpaymentsprofilerequestdetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createrecurringpaymentsprofilerequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createrecurringpaymentsprofileresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'createrecurringpaymentsprofileresponsetype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'creditcarddetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'creditcardnumbertypetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'devicedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'discounttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'displaycontroldetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doauthorizationreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doauthorizationrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doauthorizationresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'docancelreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'docancelrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'docancelresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'docapturereq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'docapturerequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'docaptureresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'docaptureresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dodirectpaymentreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dodirectpaymentrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dodirectpaymentrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dodirectpaymentresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doexpresscheckoutpaymentreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doexpresscheckoutpaymentrequestdetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doexpresscheckoutpaymentrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doexpresscheckoutpaymentresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doexpresscheckoutpaymentresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'domobilecheckoutpaymentreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'domobilecheckoutpaymentrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'domobilecheckoutpaymentresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'domobilecheckoutpaymentresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dononreferencedcreditreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dononreferencedcreditrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dononreferencedcreditrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dononreferencedcreditresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dononreferencedcreditresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreauthorizationreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreauthorizationrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreauthorizationresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreferencetransactionreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreferencetransactionrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreferencetransactionrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreferencetransactionresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'doreferencetransactionresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'douatpauthorizationreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'douatpauthorizationrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'douatpauthorizationresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'douatpexpresscheckoutpaymentreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'douatpexpresscheckoutpaymentrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'douatpexpresscheckoutpaymentresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dovoidreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dovoidrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'dovoidresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'ebayitempaymentdetailsitemtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedcancelrecouprequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedcheckoutdatatype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedcompleterecouprequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedcompleterecoupresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhanceddatatype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedinitiaterecouprequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhanceditemdatatype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedpayerinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedpaymentdatatype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enhancedpaymentinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enterboardingreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enterboardingrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enterboardingrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'enterboardingresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'errordata' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'errorparameter' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'errorparametertype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'errortype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'executecheckoutoperationsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'executecheckoutoperationsrequestdetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'executecheckoutoperationsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'executecheckoutoperationsresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'executecheckoutoperationsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'externalpartnertrackingdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'externalremembermeoptindetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'externalremembermeoptoutreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'externalremembermeoptoutrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'externalremembermeoptoutresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'externalremembermeownerdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'externalremembermestatusdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'faultmessage' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'flightdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'flowcontroldetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'fmfdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'formatterfactory' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/formatters/FormatterFactory.php',
        'fundingsourcedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getaccesspermissiondetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getaccesspermissiondetailsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getaccesspermissiondetailsresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getaccesspermissiondetailsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getaccesstokenrequest' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getaccesstokenresponse' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getadvancedpersonaldatarequest' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getadvancedpersonaldataresponse' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getauthdetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getauthdetailsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getauthdetailsresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getauthdetailsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getbalancereq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getbalancerequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getbalanceresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getbasicpersonaldatarequest' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getbasicpersonaldataresponse' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getbillingagreementcustomerdetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getbillingagreementcustomerdetailsrequesttype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getbillingagreementcustomerdetailsresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getbillingagreementcustomerdetailsresponsetype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getboardingdetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getboardingdetailsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getboardingdetailsresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getboardingdetailsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getexpresscheckoutdetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getexpresscheckoutdetailsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getexpresscheckoutdetailsresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getexpresscheckoutdetailsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getincentiveevaluationreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getincentiveevaluationrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getincentiveevaluationrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getincentiveevaluationresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getincentiveevaluationresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getmobilestatusreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getmobilestatusrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getmobilestatusrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getmobilestatusresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getpaldetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getpaldetailsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getpaldetailsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getpermissionsrequest' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getpermissionsresponse' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'getrecurringpaymentsprofiledetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getrecurringpaymentsprofiledetailsrequesttype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getrecurringpaymentsprofiledetailsresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'getrecurringpaymentsprofiledetailsresponsetype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'gettransactiondetailsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'gettransactiondetailsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'gettransactiondetailsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'identificationinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'identitytokeninfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentiveapplieddetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentiveappliedtotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentiveapplyindicationtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentivebuckettype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentivedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentivedetailtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentiveinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentiveitemtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'incentiverequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'infosharingdirectivestype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'initiaterecoupreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'initiaterecouprequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'initiaterecoupresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'installmentdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'instrumentdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'invoiceitemtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'ippcredential' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/IPPCredential.php',
        'ippformatter' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/formatters/IPPFormatter.php',
        'ipphandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/IPPHandler.php',
        'ippthirdpartyauthorization' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/IPPThirdPartyAuthorization.php',
        'itemtrackingdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managependingtransactionstatusreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managependingtransactionstatusrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managependingtransactionstatusresponsetype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managerecurringpaymentsprofilestatusreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managerecurringpaymentsprofilestatusrequestdetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managerecurringpaymentsprofilestatusrequesttype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managerecurringpaymentsprofilestatusresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'managerecurringpaymentsprofilestatusresponsetype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'masspayreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'masspayrequestitemtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'masspayrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'masspayresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'measuretype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'merchantdatatype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'merchantpullinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'merchantpullpaymentresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'merchantpullpaymenttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'merchantstoredetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'mobileidinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'mockoauthdatastore' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/AuthUtil.php',
        'oauthconsumer' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthdatastore' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthexception' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthrequest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthserver' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthsignaturemethod' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthsignaturemethod_hmac_sha1' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthsignaturemethod_plaintext' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthsignaturemethod_rsa_sha1' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthtoken' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'oauthutil' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPAuth.php',
        'offercouponinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'offerdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'optiondetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'optionselectiondetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'optiontrackingdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'optiontype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'orderdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'otherpaymentmethoddetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'payerinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymentdetailsitemtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymentdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymentdirectivestype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymentinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymentiteminfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymentitemtype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymentrequestinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymenttransactionsearchresulttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paymenttransactiontype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'paypalapiinterfaceserviceservice' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceServiceService.php',
        'permissionsservice' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/PermissionsService.php',
        'personalattributelist' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'personaldata' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'personaldatalist' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'personnametype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'phonenumbertype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'ppapicontext' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/common/PPApiContext.php',
        'ppapiservice' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPAPIService.php',
        'ppapiservicetest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPAPIServiceTest.php',
        'pparrayutil' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/common/PPArrayUtil.php',
        'ppauthenticationhandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/PPAuthenticationHandler.php',
        'ppbaseservice' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPBaseService.php',
        'ppbaseservicetest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPBaseServiceTest.php',
        'ppcertificateauthhandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/PPCertificateAuthHandler.php',
        'ppcertificatecredential' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPCertificateCredential.php',
        'ppcertificatecredentialtest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPCertificateCredentialTest.php',
        'ppconfigmanager' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPConfigManager.php',
        'ppconfigmanagertest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPConfigManagerTest.php',
        'ppconfigurationexception' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/exceptions/PPConfigurationException.php',
        'ppconfigurationexceptiontest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPConfigurationExceptionTest.php',
        'ppconnectionexception' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/exceptions/PPConnectionException.php',
        'ppconnectionexceptiontest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPConnectionExceptionTest.php',
        'ppconnectionmanager' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPConnectionManager.php',
        'ppconnectionmanagertest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPConnectionManagerTest.php',
        'ppconstants' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPConstants.php',
        'ppcredentialmanager' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPCredentialManager.php',
        'ppcredentialmanagertest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPCredentialManagerTest.php',
        'ppgenericservicehandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/PPGenericServiceHandler.php',
        'pphttpconfig' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPHttpConfig.php',
        'pphttpconnection' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPHttpConnection.php',
        'ppinvalidcredentialexception' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/exceptions/PPInvalidCredentialException.php',
        'ppinvalidcredentialexceptiontest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPInvalidCredentialExceptionTest.php',
        'ppipnmessage' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/ipn/PPIPNMessage.php',
        'ppipnmessagetest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPIPNMessageTest.php',
        'pplogginglevel' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPLoggingManager.php',
        'pploggingmanager' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPLoggingManager.php',
        'pploggingmanagertest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPLoggingManagerTest.php',
        'ppmerchantservicehandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/PPMerchantServiceHandler.php',
        'ppmessage' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPMessage.php',
        'ppmessagetest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPMessageTest.php',
        'ppmissingcredentialexception' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/exceptions/PPMissingCredentialException.php',
        'ppmissingcredentialexceptiontest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPMissingCredentialExceptionTest.php',
        'ppmodel' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/common/PPModel.php',
        'ppnvpformatter' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/formatters/PPNVPFormatter.php',
        'ppopenidaddress' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/openid/PPOpenIdAddress.php',
        'ppopenidaddresstest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/openid/PPOpenIdAddressTest.php',
        'ppopeniderror' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/openid/PPOpenIdError.php',
        'ppopenidhandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/PPOpenIdHandler.php',
        'ppopenidsession' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/openid/PPOpenIdSession.php',
        'ppopenidsessiontest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/openid/PPOpenIdSessionTest.php',
        'ppopenidtokeninfo' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/openid/PPOpenIdTokeninfo.php',
        'ppopenidtokeninfotest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/openid/PPOpenIdTokeninfoTest.php',
        'ppopeniduserinfo' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/openid/PPOpenIdUserinfo.php',
        'ppopeniduserinfotest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/openid/PPOpenIdUserinfoTest.php',
        'ppplatformservicehandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/PPPlatformServiceHandler.php',
        'ppreflectionutil' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/common/PPReflectionUtil.php',
        'pprequest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPRequest.php',
        'pprestcall' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/transport/PPRestCall.php',
        'ppsignatureauthhandler' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/handlers/PPSignatureAuthHandler.php',
        'ppsignaturecredential' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPSignatureCredential.php',
        'ppsignaturecredentialtest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPSignatureCredentialTest.php',
        'ppsoapformatter' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/formatters/PPSOAPFormatter.php',
        'ppsubjectauthorization' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPSubjectAuthorization.php',
        'pptokenauthorization' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/auth/PPTokenAuthorization.php',
        'pptransformerexception' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/exceptions/PPTransformerException.php',
        'ppuseragent' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/common/PPUserAgent.php',
        'pputils' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPUtils.php',
        'pputilstest' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPUtilsTest.php',
        'ppxmlmessage' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPXmlMessage.php',
        'receiverinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'recurringpaymentsprofiledetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'recurringpaymentssummarytype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'referencecreditcarddetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'refreshtokenstatusdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'refundinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'refundtransactionreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'refundtransactionrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'refundtransactionresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'remembermeidinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'requestenvelope' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'requestpermissionsrequest' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'requestpermissionsresponse' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'responseenvelope' => 'lib/paypal/paypal-permissions-sdk-php-ea09fea/lib/services/Permissions/Permissions.php',
        'reversetransactionreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'reversetransactionrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'reversetransactionrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'reversetransactionresponsedetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'reversetransactionresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'riskfilterdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'riskfilterlisttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'scheduledetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'sellerdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'senderdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setaccesspermissionsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setaccesspermissionsrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setaccesspermissionsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setaccesspermissionsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setauthflowparamreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setauthflowparamrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setauthflowparamrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setauthflowparamresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setcustomerbillingagreementreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setcustomerbillingagreementrequestdetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setcustomerbillingagreementrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setcustomerbillingagreementresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setdatarequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setdataresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setexpresscheckoutreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setexpresscheckoutrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setexpresscheckoutrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setexpresscheckoutresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setmobilecheckoutreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setmobilecheckoutrequestdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setmobilecheckoutrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'setmobilecheckoutresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'shippingoptiontype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'simplecontainertestclass' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPMessageTest.php',
        'simpletestclass' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/tests/PPMessageTest.php',
        'subscriptioninfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'subscriptiontermstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'taxiddetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'threedsecureinfotype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'threedsecurerequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'threedsecureresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'transactionsearchreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'transactionsearchrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'transactionsearchresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'tupletype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'uatpdetailstype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updateaccesspermissionsreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updateaccesspermissionsrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updateaccesspermissionsresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updateauthorizationreq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updateauthorizationrequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updateauthorizationresponsetype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updaterecurringpaymentsprofilereq' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updaterecurringpaymentsprofilerequestdetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updaterecurringpaymentsprofilerequesttype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updaterecurringpaymentsprofileresponsedetailstype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'updaterecurringpaymentsprofileresponsetype' =>
            'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'userselectedoptiontype' => 'lib/paypal/paypal-merchant-sdk-php-4f570f5/lib/services/PayPalAPIInterfaceService/PayPalAPIInterfaceService.php',
        'xmltoarray' => 'lib/paypal/paypal-sdk-core-php-2ee73c7/lib/PPUtils.php',
        );

    public static function loadClass($class) {
        $class = strtolower(trim($class, '/'));

        if (isset(self::$map[$class])) {
            require dirname(__FILE__) . '/' . self::$map[$class];
        }
    }

    public static function register() {
        spl_autoload_register(array(__CLASS__, 'loadClass'), true);
    }
}
